### ISSUE TITLE
bro how to fix

### ISSUE THREAD

**Issue by colourfulhacker** [webdeveloperkanai/cehpoint-eleaning-bot#1]
Traceback (most recent call last):
  File "bot.py", line 2, in <module>
    from pyfiglet import Figlet
ImportError: No module named pyfiglet
 

Collecting pyfiglet==0.7
  Downloading pyfiglet-0.7.tar.gz (691 kB)
     |████████████████████████████████| 691 kB 405 kB/s 
Building wheels for collected packages: pyfiglet
  Building wheel for pyfiglet (setup.py) ... done
  Created wheel for pyfiglet: filename=pyfiglet-0.7-py3-none-any.whl size=847078 sha256=88f183fcd19ce9897bfa3c4f29ab7a421afaf046ab40cbb33b206792ff7db309
  Stored in directory: /root/.cache/pip/wheels/d1/b6/e3/fcb5c329c7825a1785b8b729cc84a586bc8ce781cbd0642670
Successfully built pyfiglet
Installing collected packages: pyfiglet
  Attempting uninstall: pyfiglet
    Found existing installation: pyfiglet 0.8.post0
    Not uninstalling pyfiglet at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pyfiglet'. No files were found to uninstall.
Successfully installed pyfiglet-0.7

**Comment by webdeveloperkanai** [comment]
Hello dear, I am very grateful for you that you noticed that this script is not working correctly. Currently I have updated this and it is working on any platform. Windows / Linux / Android / Mac everywhere

**Comment by konkomaji** [comment]
hi guys
